### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by Knifa** [RFExplorer/RFExplorer-for-Python#1]
Please follow standard Python conventions and use [PEP8](https://www.python.org/dev/peps/pep-0008/). Hungarian notation is a huge no-no among other violations throughout the library.

**Comment by arocholl** [comment]
Thanks for the suggestion - unfortunately PEP8 or other PEP standards are not easy to implement for the library. The reason is we  keep the Python library as a mirror of the .NET library, so both get same features at the same time.

Using different notation would increase our dev cost significantly.

What we can do is apply full PEP standard to the code examples. Do you think that would help?

**Comment by Knifa** [comment]
Thanks for the reply @arocholl. Understandable --- are stubs generated from the .NET library or something similar?

Code examples in PEP8 would be great, though! I'm happy to work on this over all as PR too if you think it would be worthwhile but it might be troublesome keeping them in sync with the .NET library in the future.

**Comment by arocholl** [comment]
No stubs generated - we just manually update the Python library from the main .NET development suite. From test and code review perspective, the only feasible way is keep same variable and function names as in .NET.

We will schedule a code update for the Python examples so can be PEP8 compatible. Again thanks for the feedback.

Not sure to understand what you mean by "work on this over all as PR too"
