### ISSUE TITLE
missing command: Change Module

### ISSUE THREAD

**Issue by philipclaesson** [RFExplorer/RFExplorer-for-Python#23]
a function for changing the module using the `#CM` command seem to be missing in this implementation.

according to the [docs](https://github.com/RFExplorer/RFExplorer-for-.NET/wiki/RF-Explorer-UART-API-interface-specification#these-are-commands-available-from-pc-to-rf-explorer-spectrum-analyzer-only):

> SwitchModuleMain | #<Size>CM<0> | Request RF Explorer to enable Mainboard module where <0> is a binary 0 byte and <Size>=5 bytes

the function would look something like:
```
    def SendCommand_ChangeModule(self, module):
        """Set RF Explorer module (0 or 1)
        """
        assert module in [0, 1]
        self.SendCommand("CM%s" % (chr(module)))
``` 

The above function seems to do what it should, but I have also been experiencing some reliability issues that may possibly be related to the usage of the `#CM` command.

Is there another recommended way to change module? Any quirks that one should be aware of?

Thanks!

**Comment by arocholl** [comment]
Your function seems correct, not all possible commands are implemented in Python because it is very easy to use a standard SendCommand with the command you need. Basically a SendCommand("CM0") and SendCommand("CM1") do what you need.

Make sure you wait 10 seconds after changing the module before sending any new command so the internal electronics stabilize.
