### ISSUE TITLE
Amplitude measure

### ISSUE THREAD

**Issue by kolki** [RFExplorer/RFExplorer-for-Python#3]
Goodday, I work with a RFexplorer (MWSUB3G module control.) IoT on raspberry Pi2 B, nice kit but i have some problems in measuring amplitude.

Let's go, I use a rohde et schwarz bench for testing accuracy with examples scripts given on github. I found something wrong. Frequency 340.250 Mhz from -95dBm to -20dBM, everything is fine but more than -20dBm, only display -24dBm and lower than -100dBM, only display -102dBm.

I found some tips with HasCalibrationData() or HasCompressionData() but they answer False. I hope i missed something and you will help me cause i really need to be able to measure between -60 and -120 dBm for this project.

Other thing, i saw each time 240 steps, but can't figure how to change it.

regards Chris

**Comment by arocholl** [comment]
Hi Kolki, sorry for the late response.

On your first question: higher values of -25dBm are setting the instrument in non linear range due to high power level. To measure signals above -30dBm, we suggest enabling the attenuator. You can do that with a SendCommand("a1"), then you can measure signal levels up to 0dBm or even a bit more without distortion.

On your second question, you can change sweep steps using SendCommand_SweepDataPoints for values 112-4096.
